### ISSUE TITLE
tor-ctrl-stream requires pressing Enter before seeing any output

### ISSUE THREAD

**Issue by adrelanos** [nyxnor/tor-ctrl#13] opened 2022-01-16 19:53 UTC
Using `tor-ctrl-stream` in Whonix-Gateway.

Is it expected that one has to press Enter before any output is shown?

**Comment by nyxnor** [comment] 2022-01-16 20:00
yes, the enter is to finish, because else the `read -r` command will read from the streams, not from the enter pressed.
If another option is found, would be great to show streams raw first.

**Comment by nyxnor** [comment] 2022-01-16 20:15
or `Ctrl+C` to quit... and send events to stdout... will check if possible.

**Comment by adrelanos** [comment] 2022-01-17 19:33
Would be ideal if it could show the streams as they are created. Live.

**Comment by adrelanos** [comment] 2022-01-17 19:36
Maybe it could be solved with a subshell?

Or perhaps easier to read by splitting into two scripts?

Does tor-ctrl have a feature to sign up for a Tor control protocol event and then just keep listening what is coming in?

If so, that output could be processed in a `while` loop in tor-ctrl-stream?

**Comment by nyxnor** [comment] 2022-01-17 19:50
> Does tor-ctrl have a feature to sign up for a Tor control protocol event and then just keep listening what is coming in?
If so, that output could be processed in a while loop in tor-ctrl-stream?

Not yet but that's THE goal for tor-ctrl-stream.

Will investigate, and as always, contributions welcome. to make this happen

**Comment by nyxnor** [comment] 2022-01-17 19:51
the initial vision for tor-ctrl-stream is to make `tor-ctrl -w SETEVENTS STREAM` clear to read, so if tor-ctrl, the main script dumps the config before enter, than that would be great and that is what I think you want.

**Comment by nyxnor** [comment] 2022-01-17 23:09
currently it is not being printed because the connection is piped to the function finish.
https://github.com/nyxnor/tor-ctrl/blob/e7c003f762f8a27c8b78d802e26121a0bc56c7f6/usr/bin/tor-ctrl#L269
https://github.com/nyxnor/tor-ctrl/blob/e7c003f762f8a27c8b78d802e26121a0bc56c7f6/usr/bin/tor-ctrl#L368

**Comment by nyxnor** [comment] 2022-01-17 23:50
I got tor-ctrl to print to screen without pressing enter, the problem is, I haven't found a way to resume back to send commands to the control.
So it keeps showing the events, including new ones, but won't let you type new commands.

```sh
## piping commands to be sent
cmd_pipe(){
  # shellcheck disable=SC2030,2031
  send_cmd "${auth_string}"
  send_cmd "${cmd_cli}"
  ## shellcheck disable=SC2034
  #cat | while IFS="$(printf "\n")" read -r a; do
  #  echo $a
  #done

  ##[ "${wait_confirmation}" -eq 1 ] && read -r confirmation
  ##send_cmd "QUIT"
}
```

```sh
    if [ -n "${wait_confirmation}" ]; then
      cmd_pipe | ${socket_prog_connect} 2>/dev/null
    else
      cmd_pipe | ${socket_prog_connect} 2>/dev/null | finish
    fi
```
you will need to Ctrl+C to stop

probably using file descriptors could help if I new how to combine if with the socket programs.

to understand and see why it get stuck, run:
```sh
echo PROTOCOLINFO | netcat 127.0.0.1 9051
```
and then try to type `QUIT`, it won't be sent.
That is the same problem that if solved, SAFECOOKIE authentication, which is more secure, would be possible (need to get the server nonce after sending an AUTHCHALLENGE, and then get servernonce and calculate and respond back.

I am trying trap 'function' int to break.

**Comment by adrelanos** [comment] 2022-01-18 11:12
Dunno. Could you try please to ask how to generally do that on the
help-bash mailing list? Usually very high quality answers there.

**Comment by nyxnor** [comment] 2022-01-19 02:06
c7a295ddc10872526efd83fb2b6346a8f71ea9ea

**Comment by adrelanos** [comment] 2022-01-19 12:25
This is amazing!

**Comment by adrelanos** [comment] 2022-01-19 12:46
I am making suggestions for an already very awesome application.

Not sure I should make separate tickets for each of these.

----

1)

I wasn't amazed to see when starting Tor Browser:

> 250-stream-status=1332 SENTCONNECT 4 firefox.settings.services.mozilla.com:443

This may or may not have a bug report on the Tor Project Tor Browser issue tracker. TBB probably doesn't want or shouldn't connect to `firefox.settings.services.mozilla.com` at first start. This does not happen on subsequent TBB starts. It's very good that tor-ctrl is showing that!

----

2)

> 250-stream-status=3639 SUCCEEDED 45 116.202.120.181:443

I didn't know what that IP is. Can be found on search engines (check.torproject.org) but that isn't comfortable to find out about unwanted connections. Could you please add reverse DNS as an additional field?

----

3)

When pressing enter, tor-ctrl-stream shouldn't exit. No application is acting like that as far as I know. I use enter key a lot to make some new lines in the console output as separator between what I already read and what is coming up. To exit the usual ctrl + c should be used.

----

4)

Suggestion:

* `--human` (default?): show a greeting message "INFO: tor-ctrl-stream subscribed to Tor event setevents-stream. As soon as streams are created, output will be shown Below. To exit, press ctrl + c."
* `--machine`: no additional explanations. This is to make the output easier to parse in scripts.

Not sure this all fits. I am looking for some tool to monitor where Tor is connecting to for the purpose of finding out about unwanted connections (bad for privacy or even malware).

----

5)

Also start menu entries would be great. This is how it's done in Whonix.

* https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/usr/libexec/gateway-shortcuts/nyx
* https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/usr/share/applications/gateway-nyx.desktop
* https://github.com/Whonix/helper-scripts/blob/master/usr/libexec/helper-scripts/terminal-wrapper

I could certainly add (and most likely would) add tor-ctrl and tor-ctrl applications start menu entries in Whonix if this cannot be done in this upstream repository (preferred). But how to implement start menu entries (graphical) for a console application  outside of Whonix is unclear to me since helper-scripts and therefore terminal-wrapper isn't installed by default. And replicating this functionality in "every" (this) repository seems to much to me. A dependency on helper-scripts might also be unwanted? If helper-scripts was available from packages.debian.org, that might make it an easier case? But not easy.

**Comment by adrelanos** [comment] 2022-01-19 12:50
6)

tor-ctrl-stream as is is OK as is for its use case. It's console output should not be published such as in public forums by users since it contains their whole circuit from Tor entry guard, middle relay and exit relay.

Could you please add a warning (only shown when not using `--machine`) that posting this contents online could de-anonymize users?

----

7)

The utility I am looking for is actually something that users can share online without risk. Not showing Tor entry/middle/exit. Only showing which IPs or onions Tor is connecting to. Then users could share this in public places, post logs without risk, report bugs about unwanted connections (privacy violations or malware). That isn't a good idea to mix into tor-ctrl-stream. A separate utility for that purpose would be cool.

**Comment by nyxnor** [comment] 2022-01-20 00:51
> This is amazing!

Thanks. The commit was small but the time to figure out how to do it was some hours.

> I am making suggestions for an already very awesome application.

At least I had 11 hours of rest. Jokes aside, if there are feature requests, the software is unfinished. Open the tickets :)

![image](https://user-images.githubusercontent.com/69700936/150241569-7627f365-23bc-4f2a-93f8-d6b5f06eb70f.png)

-----

1. The last issue about it was closed 2 years ago - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/31575 - so probably a new issue is needed. Good catch.

----------------

2. This is worth an new issue.
I expected you to see the domain name on the line `SENTCONNECT`, curled check.torproject.org 2 times:
```
250-stream-status=105024 NEW 0 check.torproject.org:443
250-stream-status=105024 SENTCONNECT 1441 check.torproject.org:443
250-stream-status=105024 SUCCEEDED 1441 116.202.120.181:443
250-stream-status=108141 SENTCONNECT 1442 check.torproject.org:443
250-stream-status=108141 SUCCEEDED 1442 116.202.120.181:443
```
but them I tested trying to connect very fast to different domains and I noticed that in fact the SENTCONNECT line or SUCCEEDED sometimes does not appear:
```
250-stream-status=109597 SUCCEEDED 1458 140.82.121.4:443
250-stream-status=109617 SUCCEEDED 1459 116.202.120.181:443
```
The case is that `GETINFO stream-status` just show one line per request and change at every new stream update, and that is horrible, very different than `GETINFO circuit-status` that dumps a lot of lines. Maybe because stream time of life is much shorter than circuits, but anyway...

This might or might not be fixed by removing sleeping time https://github.com/nyxnor/tor-ctrl/blob/6c09bfc1430a7225e7681f2f05013d66af800974/usr/bin/tor-ctrl-stream#L36, which is to protect against looping too much.
It would only be fixed if the loop occurs faster than any stream update its status.

How to do reverse DNS lookup over Tor, does Whonix has a Wiki for that?
Also, If I perform a reverse dns lookup, wouldn't that create a new stream for that lookup? That could be uncessary if `stream-status` just dumped more lines...

Anyway, the docs of possibly evil cloudflare, about dns lookup over Tor (the example is with socat, which is not working as expected on whonix so not sure this will be successful):
https://developers.cloudflare.com/1.1.1.1/other-ways-to-use-1.1.1.1/dns-over-tor#dns-over-tcp-tls-and-https
> The hidden resolver is set up to listen on TCP ports 53 and 853 for DNS over TCP and TLS. After setting up a Tor proxy, run the following socat command as a privileged user, replacing the port number appropriately:
```sh
PORT=853; socat TCP4-LISTEN:${PORT},reuseaddr,fork SOCKS4A:127.0.0.1:dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion:${PORT},socksport=9150
```
> From here, you can follow the regular [guide for Setting up 1.1.1.1](https://developers.cloudflare.com/1.1.1.1/setup-1.1.1.1/linux), except you should always use 127.0.0.1 instead of 1.1.1.1. If you need to access the proxy from another device, simply replace 127.0.0.1 in socat commands with your local IP address.

https://developers.cloudflare.com/1.1.1.1/other-ways-to-use-1.1.1.1/dns-over-tor#dns-over-udp
> Note that the Tor network does not support UDP connections, which is why some hacking is needed. If your client only supports UDP connections, the solution is to encapsulate packets to port UDP:53 on localhost as TCP packets, using the following socat command:
```sh
socat UDP4-LISTEN:53,reuseaddr,fork SOCKS4A:127.0.0.1:dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion:253,socksport=9150
```

---------------

3.
> When pressing enter, tor-ctrl-stream shouldn't exit. [...] . To exit the usual ctrl + c should be used.

Worth a new issue so this can be improved.

I tried to sigint but didn't work and enter was the easy method for now.

The problem relies on: If I allow only `Ctrl+C` interrupt signal to quit `tor-ctrl -w`, if I run `tor-ctrl-stream`, how do I send interrupt signal just to the child process? I don't know if this is possible and at the time I was coding yesterday, did some tries with traps on tor-ctrl-stream to resume and didn't work, but could retry again.

Just letting you know that exit code does not work with `-w` as the function finish is never called because it wouldnt output to screen if the connection is closed by sending the command quit, which is the third ^250 reply. But as it is more like a log style with SETEVENTS than a request for specific information as in GETINFO and GETCONF, and not  compatible with `-q` quiet mode, as it would defeat the whole purpose of waiting for a reply, I think it is acceptable the way it is.

-----

4. Yes, warning should be made. Worth a new issue.

-----

5.
> If helper-scripts was available from packages.debian.org, that might make it an easier case?

Yes, as adding terminal-wrapper script here would be as you said, replicating and too much. The shortcuts and .desktop are okay, but I will have to wait for an update status about this issue.

------

6. When you open the issue related to point 4, also mention this, as it can be done together.

--------

7.
Worth a new issue. Describe the format you would like.
* `GETINFO stream-status` for a one line of the last status of a stream if any
* `SETEVENTS STREAM` for asynchronous replies of stream, which is hard to read.

> That isn't a good idea to mix into tor-ctrl-stream

Maybe I could make a `--obfuscate` option to not show circuit path, just `stream circ target`. But yeah, would lose the meaning of using tor-ctrl-stream and people may forget to use that option, so better not even run that script at all if they want to share?

**Comment by nyxnor** [comment] 2022-01-20 10:40
about resolving dns lookups:
https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n1491
Need to listen for ADDRMAP.
```sh
tor-ctrl -w SETEVENTS ADDRMAP
```
on another tab
```sh
tor-ctrl RESOLVE 116.202.120.181 mode=reverse
```
reply on ADDRMAP is:
```sh
250 OK
250 OK
650 ADDRMAP 116.202.120.181 check-01.torproject.org "2022-01-20 00:00:00" EXPIRES="2022-01-20 00:00:00" CACHED="NO" STREAMID=174192
```

or if I do in one take:
```sh
tor-ctrl -w SETEVENTS ADDRMAP \\n RESOLVE 116.202.120.181 mode=reverse
```
```sh
250 OK
250 OK
250 OK
650 ADDRMAP 116.202.120.181 check-01.torproject.org "2022-01-20 00:00:00" EXPIRES="2022-01-20 00:00:00" CACHED="NO" STREAMID=174269
```
but this creates another stream of course: `650 STREAM 174281 NEWRESOLVE 0 116.202.120.181:0 PURPOSE=DNS_REQUEST`

**Closed** 2022-01-21 11:11 UTC

**Comment by nyxnor** [comment] 2022-01-21 11:14
I closed this issue because not `tor-ctrl -w` quits with INT and `tor-ctrl-stream` resumes. I think this was what you wanted so this is closed.

For the issues mentioned above, I will start looking more deep into after they are opened.

**Comment by nyxnor** [comment] 2022-01-21 18:43
> I wasn't amazed to see when starting Tor Browser:

issue opened here https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40788
